name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Test Container
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-test -f ./client/Dockerfile.dev ./client
      - name: Run Tests
        run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/react-test npm test

      - name: Build Client
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-client ./client
      - name: Build Nginx
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-nginx ./nginx
      - name: Build API
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-api ./api
      - name: Build Worker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-worker ./worker

      - name: Push Client
        run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-client
      - name: Push Nginx
        run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-nginx
      - name: Push API
        run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-api
      - name: Push Worker
        run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: MultiDocker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-227786593147
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip